import catan from "../images/Catan_Track.png"
import catanPDF from '../resources/catan_tracker.pdf'
import weather from "../images/weather.jpg"
import myFace from "../images/me.jpg"
import slasher from "../images/slasher.png"

function Projects() {

    return(
        <div id="projects" className="">
            <h2 className="offset-1">Projects</h2>
            <ProjectsGroup />
        </div>
    )
}//end method

function ProjectsGroup() {
    const data = [
        {
            imgSrc : catan, 
            title : "Catan Tracker (C#)", 
            body : "My Catan Tracking WPF Application. I created this application for my extended family. They love playing Catan and keeping track of the data generated by gameplay. The front end is XAML and back end is C#",
            link : catanPDF,
            linkText : "Overview",
            git : "https://github.com/Jonathan-Pruitt/MSCodingProjects/tree/main/CatanTrackerV2.4"
        }, 
        {
            imgSrc : slasher, 
            title: "SLASHER", 
            body : "A 2D simple action game I created using JavaScript, and rendering through the 'canvas' HTML element. I struggled a bit creating the game engine to handle rotation and angle checks, and my lack of JavaScript expertise led to some clunky code. However, I am proud of the finished product!",
            link : "https://jonathan-pruitt.github.io/SLASHER/",
            linkText : "Play SLASHER",
            git : "https://github.com/Jonathan-Pruitt/SLASHER"
        }, 
        {
            imgSrc : weather, 
            title : "Weather Forecast", 
            body : "This web application grabs your geolocation, then runs an AJAX request against the NWS (National Weather Service) api and renders the response data for a 1 week forecast. This was my first API project in HTML/CSS/JS. The images were self-created, and I had not yet learned bootstrap. The mobile version will look a little wonky.",
            link : "https://jonathan-pruitt.github.io/Forecast-Site/",
            linkText : "Site",
            git : "https://github.com/Jonathan-Pruitt/Forecast-Site"
        }, 
        {
            imgSrc : myFace, 
            title: "Jonathan Pruitt GitHub", 
            body : "Take a moment to check out some of my other work on GitHub!",
            git : "https://github.com/Jonathan-Pruitt"
        }
    ]

    const group = data.map(tile =>         
        <ProjectTile 
            title={tile.title} 
            body={tile.body}   
            imgSrc={tile.imgSrc}
            link={tile.link}
            linkText={tile.linkText} 
            git={tile.git}        
        />
    )

    return (
        <div className="row justify-content-center">
            {group}
        </div>
    )
}

function ProjectTile(props){
// Catan Tracker -- Game -- Weather Forecast -- Github Link    

    return (
        <div className="card p-3 col-10 pop">
            <img className="card-img-top bordered l-shadowed" src={props.imgSrc} alt="Card image cap"/>
            <div className="card-body">
                <h3>{props.title}</h3>
                <p className="card-text">{props.body}</p>
                <div className="row">
                    {props.link && <a className="col" href={props.link} target="_blank">{props.linkText}&#128279;</a>}
                    <a className="col" href={props.git} target="_blank">GitHub&#128279;</a>
                </div>
            </div>
        </div>    
    )
}

export default Projects;